# Azure AI Document Intelligence - Ansible Playbook
# Configuration playbook for Azure AI Document Intelligence solution

---
- name: Configure Azure AI Document Intelligence
  hosts: localhost
  gather_facts: false
  connection: local
  
  vars:
    resource_group_name: "rg-doc-intelligence-prod-001"
    location: "East US 2"
    cognitive_services_name: "cs-doc-intelligence-prod-001"
    
  tasks:
    - name: Ensure Azure CLI is available
      command: az --version
      register: az_version
      
    - name: Configure Document Intelligence service
      shell: |
        az cognitiveservices account create \
          --name {{ cognitive_services_name }} \
          --resource-group {{ resource_group_name }} \
          --kind FormRecognizer \
          --sku S0 \
          --location "{{ location }}"