#!/bin/bash
#------------------------------------------------------------------------------
# EO Framework - Terraform State Backend Setup
# HashiCorp Multi-Cloud Platform
#------------------------------------------------------------------------------
# Creates S3 bucket and DynamoDB table for Terraform remote state
#------------------------------------------------------------------------------

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Default values
ENVIRONMENT=${1:-prod}
REGION=${2:-us-east-1}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_DIR="$ROOT_DIR/environments/$ENVIRONMENT"

echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}EO Framework - State Backend Setup${NC}"
echo -e "${GREEN}Environment: $ENVIRONMENT${NC}"
echo -e "${GREEN}Region: $REGION${NC}"
echo -e "${GREEN}============================================${NC}"

# Read solution abbreviation from project.tfvars
if [ -f "$ENV_DIR/config/project.tfvars" ]; then
    SOLUTION_ABBR=$(grep -E "^\s*abbr\s*=" "$ENV_DIR/config/project.tfvars" | head -1 | cut -d'"' -f2)
else
    SOLUTION_ABBR="mcp"
fi

# Generate unique identifiers
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
STATE_BUCKET="tfstate-${SOLUTION_ABBR}-${ENVIRONMENT}-${AWS_ACCOUNT_ID}"
LOCK_TABLE="tfstate-${SOLUTION_ABBR}-${ENVIRONMENT}-lock"
STATE_KEY="${SOLUTION_ABBR}/${ENVIRONMENT}/terraform.tfstate"

echo -e "${YELLOW}Creating S3 bucket: $STATE_BUCKET${NC}"

# Create S3 bucket (handle us-east-1 special case)
if [ "$REGION" = "us-east-1" ]; then
    aws s3api create-bucket \
        --bucket "$STATE_BUCKET" \
        --region "$REGION" 2>/dev/null || echo "Bucket may already exist"
else
    aws s3api create-bucket \
        --bucket "$STATE_BUCKET" \
        --region "$REGION" \
        --create-bucket-configuration LocationConstraint="$REGION" 2>/dev/null || echo "Bucket may already exist"
fi

# Enable versioning
echo -e "${YELLOW}Enabling versioning...${NC}"
aws s3api put-bucket-versioning \
    --bucket "$STATE_BUCKET" \
    --versioning-configuration Status=Enabled

# Enable encryption
echo -e "${YELLOW}Enabling encryption...${NC}"
aws s3api put-bucket-encryption \
    --bucket "$STATE_BUCKET" \
    --server-side-encryption-configuration '{
        "Rules": [{
            "ApplyServerSideEncryptionByDefault": {
                "SSEAlgorithm": "aws:kms"
            },
            "BucketKeyEnabled": true
        }]
    }'

# Block public access
echo -e "${YELLOW}Blocking public access...${NC}"
aws s3api put-public-access-block \
    --bucket "$STATE_BUCKET" \
    --public-access-block-configuration '{
        "BlockPublicAcls": true,
        "IgnorePublicAcls": true,
        "BlockPublicPolicy": true,
        "RestrictPublicBuckets": true
    }'

# Create DynamoDB table for state locking
echo -e "${YELLOW}Creating DynamoDB table: $LOCK_TABLE${NC}"
aws dynamodb create-table \
    --table-name "$LOCK_TABLE" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$REGION" 2>/dev/null || echo "Table may already exist"

# Wait for table to be active
echo -e "${YELLOW}Waiting for DynamoDB table to be active...${NC}"
aws dynamodb wait table-exists --table-name "$LOCK_TABLE" --region "$REGION"

# Generate backend.tfvars
BACKEND_FILE="$ENV_DIR/backend.tfvars"
echo -e "${YELLOW}Generating backend config: $BACKEND_FILE${NC}"

cat > "$BACKEND_FILE" << EOF
# Auto-generated by state-backend.sh
# Run: terraform init -backend-config=backend.tfvars

bucket         = "$STATE_BUCKET"
key            = "$STATE_KEY"
region         = "$REGION"
dynamodb_table = "$LOCK_TABLE"
encrypt        = true
EOF

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}State backend created successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "S3 Bucket:      $STATE_BUCKET"
echo "DynamoDB Table: $LOCK_TABLE"
echo "State Key:      $STATE_KEY"
echo ""
echo "Next steps:"
echo "  cd $ENV_DIR"
echo "  terraform init -backend-config=backend.tfvars"
echo ""
