---
# Cisco SD-WAN Enterprise Inventory
# This inventory defines the SD-WAN infrastructure components

all:
  children:
    sdwan_controllers:
      children:
        vmanage:
          hosts:
            vmanage-01:
              ansible_host: 10.1.1.10
              system_ip: 10.255.255.10
              site_id: 1
              device_type: vmanage
              
        vbond:
          hosts:
            vbond-01:
              ansible_host: 10.1.1.11  
              system_ip: 10.255.255.11
              site_id: 1
              device_type: vbond
              
        vsmart:
          hosts:
            vsmart-01:
              ansible_host: 10.1.1.12
              system_ip: 10.255.255.12
              site_id: 100
              device_type: vsmart
            vsmart-02:
              ansible_host: 10.1.1.13
              system_ip: 10.255.255.13
              site_id: 100
              device_type: vsmart
              
    vedge:
      children:
        branch_routers:
          hosts:
            vedge-branch-01:
              ansible_host: 10.2.1.10
              system_ip: 10.255.255.20
              site_id: 200
              device_type: vedge
              wan_interfaces:
                - interface: "GigabitEthernet0/0/0"
                  color: "biz-internet"
                  encapsulation: "ipsec"
                  bandwidth: 100000
                  carrier: "default"
                - interface: "GigabitEthernet0/0/1"  
                  color: "mpls"
                  encapsulation: "ipsec"
                  bandwidth: 50000
                  carrier: "carrier1"
              lan_interfaces:
                - interface: "GigabitEthernet0/0/2"
                  ip_address: "192.168.200.1"
                  subnet_mask: "255.255.255.0"
                  
            vedge-branch-02:
              ansible_host: 10.2.2.10
              system_ip: 10.255.255.21
              site_id: 201
              device_type: vedge
              wan_interfaces:
                - interface: "GigabitEthernet0/0/0"
                  color: "biz-internet"
                  encapsulation: "ipsec"
                  bandwidth: 100000
                - interface: "GigabitEthernet0/0/1"
                  color: "lte"
                  encapsulation: "ipsec"
                  bandwidth: 25000
              lan_interfaces:
                - interface: "GigabitEthernet0/0/2"
                  ip_address: "192.168.201.1"
                  subnet_mask: "255.255.255.0"
                  
        hub_routers:
          hosts:
            vedge-hub-01:
              ansible_host: 10.3.1.10
              system_ip: 10.255.255.30
              site_id: 300
              device_type: vedge
              wan_interfaces:
                - interface: "GigabitEthernet0/0/0"
                  color: "biz-internet"
                  encapsulation: "ipsec"
                  bandwidth: 1000000
                - interface: "GigabitEthernet0/0/1"
                  color: "mpls"
                  encapsulation: "ipsec"
                  bandwidth: 500000
              lan_interfaces:
                - interface: "GigabitEthernet0/0/2"
                  ip_address: "192.168.100.1"
                  subnet_mask: "255.255.255.0"

  vars:
    # Global SD-WAN Configuration
    sdwan_organization: "ENTERPRISE-SDWAN"
    sdwan_domain_id: 1
    
    # Authentication
    ansible_user: "{{ vault_sdwan_username | default('admin') }}"
    ansible_password: "{{ vault_sdwan_password | default('admin123') }}"
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: true
    ansible_become_method: enable
    
    # Certificate Configuration
    vedge_devices:
      - system_ip: "10.255.255.20"
        chassis_number: "C8K-1234567890"
        serial_number: "ABC123"
      - system_ip: "10.255.255.21" 
        chassis_number: "C8K-1234567891"
        serial_number: "ABC124"
      - system_ip: "10.255.255.30"
        chassis_number: "C8K-1234567892"
        serial_number: "ABC125"
    
    # Policy Configuration
    site_lists:
      - name: "Branch_Sites"
        description: "All branch office sites"
        list_id: "branch-sites-001"
        sites:
          - "200-299"
          
      - name: "Hub_Sites"
        description: "Hub and data center sites"
        list_id: "hub-sites-001"
        sites:
          - "300-399"
          
    application_lists:
      - name: "Business_Critical"
        description: "Business critical applications"
        list_id: "business-critical-001"
        applications:
          - "microsoft-office365"
          - "salesforce"
          - "webex"
          
      - name: "Recreational"
        description: "Non-business applications" 
        list_id: "recreational-001"
        applications:
          - "youtube"
          - "facebook"
          - "netflix"
          
    centralized_policies:
      - name: "Branch_QoS_Policy"
        description: "QoS policy for branch sites"
        definition:
          sequences:
            - sequence_id: 10
              sequence_name: "Business_Critical_Apps"
              base_action: accept
              actions:
                - type: "set"
                  parameter: "dscp"
                  value: 46
              match:
                app_list: "Business_Critical"
            - sequence_id: 20
              sequence_name: "Recreational_Apps"
              base_action: accept
              actions:
                - type: "set"
                  parameter: "dscp" 
                  value: 8
              match:
                app_list: "Recreational"