# Microsoft CMMC Enclave - Compliance Framework Configuration
# CMMC Level 2 Implementation based on NIST SP 800-171 Rev 2

cmmc_framework:
  version: "2.0"
  level: 2
  nist_baseline: "SP 800-171 Rev 2"
  total_practices: 110
  
  # CMMC Level 2 Domains and Practices
  domains:
    # Access Control (AC) - 22 practices
    access_control:
      domain_id: "AC"
      name: "Access Control"
      description: "Limit information system access to authorized users, processes acting on behalf of authorized users, or devices"
      practices_count: 22
      practices:
        - id: "AC.1.001"
          title: "Limit information system access to authorized users"
          nist_control: "3.1.1"
          azure_implementation: "Azure AD Conditional Access, RBAC"
          automated: true
        - id: "AC.1.002" 
          title: "Limit information system access to the types of transactions and functions that authorized users are permitted"
          nist_control: "3.1.2"
          azure_implementation: "Azure RBAC, PIM"
          automated: true
        - id: "AC.2.003"
          title: "Control information posted or processed on publicly accessible information systems"
          nist_control: "3.1.3"
          azure_implementation: "Azure Information Protection, DLP"
          automated: true
        - id: "AC.2.004"
          title: "Control the flow of CUI in accordance with approved authorizations"
          nist_control: "3.1.4"
          azure_implementation: "Microsoft Purview, Information Protection"
          automated: true
        - id: "AC.2.005"
          title: "Separate the duties of individuals to reduce the risk of malevolent activity"
          nist_control: "3.1.5"
          azure_implementation: "Azure AD Privileged Identity Management"
          automated: true
        - id: "AC.2.006"
          title: "Connect to external information systems only through managed interfaces"
          nist_control: "3.1.6"
          azure_implementation: "Azure Firewall, Private Endpoints"
          automated: true
        - id: "AC.2.007"
          title: "Employ the principle of least privilege"
          nist_control: "3.1.7"
          azure_implementation: "Azure RBAC, Just-in-Time Access"
          automated: true
        - id: "AC.2.008"
          title: "Use non-privileged accounts or roles when accessing nonsecurity functions"
          nist_control: "3.1.8"
          azure_implementation: "Azure AD PIM, Conditional Access"
          automated: true
        - id: "AC.2.009"
          title: "Limit unsuccessful logon attempts"
          nist_control: "3.1.9"
          azure_implementation: "Azure AD Account Lockout Policies"
          automated: true
        - id: "AC.2.010"
          title: "Use session lock with pattern-hiding displays"
          nist_control: "3.1.10"
          azure_implementation: "Windows Security Policy, Intune"
          automated: true
        - id: "AC.2.011"
          title: "Authorize wireless access prior to allowing such connections"
          nist_control: "3.1.11"
          azure_implementation: "Azure Network Security Groups, Wi-Fi Policies"
          automated: true
        - id: "AC.2.012"
          title: "Control remote access sessions"
          nist_control: "3.1.12"
          azure_implementation: "Azure Bastion, Conditional Access"
          automated: true
        - id: "AC.2.013"
          title: "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions"
          nist_control: "3.1.13"
          azure_implementation: "TLS 1.3, IPSec VPN"
          automated: true
        - id: "AC.2.014"
          title: "Route remote access via managed access control points"
          nist_control: "3.1.14"
          azure_implementation: "Azure Application Gateway, Front Door"
          automated: true
        - id: "AC.2.015"
          title: "Authorize remote execution of privileged commands and remote access to security-relevant information"
          nist_control: "3.1.15"
          azure_implementation: "Azure AD PIM, JIT Access"
          automated: true
        - id: "AC.2.016"
          title: "Authorize wireless access prior to allowing such connections"
          nist_control: "3.1.16"
          azure_implementation: "Network Access Control, 802.1X"
          automated: true

    # Audit and Accountability (AU) - 9 practices
    audit_accountability:
      domain_id: "AU"
      name: "Audit and Accountability"
      description: "Create, protect, and retain information system audit records"
      practices_count: 9
      practices:
        - id: "AU.2.041"
          title: "Ensure that the actions of individual system users can be uniquely traced"
          nist_control: "3.3.1"
          azure_implementation: "Azure Monitor, Log Analytics"
          automated: true
        - id: "AU.2.042"
          title: "Create and retain system audit logs and records"
          nist_control: "3.3.2"
          azure_implementation: "Azure Audit Logs, Log Analytics Workspace"
          automated: true
        - id: "AU.2.043"
          title: "Alert in the event of an audit logging process failure"
          nist_control: "3.3.3"
          azure_implementation: "Azure Monitor Alerts, Sentinel"
          automated: true
        - id: "AU.2.044"
          title: "Review and update logged events"
          nist_control: "3.3.4"
          azure_implementation: "Azure Policy, Compliance Manager"
          automated: true
        - id: "AU.2.045"
          title: "Correlate audit record review, analysis, and reporting processes for investigation and response"
          nist_control: "3.3.5"
          azure_implementation: "Azure Sentinel, Security Center"
          automated: true
        - id: "AU.2.046"
          title: "Provide audit record reduction and report generation"
          nist_control: "3.3.6"
          azure_implementation: "Azure Workbooks, Power BI"
          automated: true
        - id: "AU.2.047"
          title: "Provide a system capability that compares and synchronizes internal system clocks"
          nist_control: "3.3.7"
          azure_implementation: "Azure NTP Service, Domain Controllers"
          automated: true
        - id: "AU.2.048"
          title: "Protect audit information and audit logging tools from unauthorized access"
          nist_control: "3.3.8"
          azure_implementation: "Azure RBAC, Key Vault"
          automated: true
        - id: "AU.2.049"
          title: "Limit management of audit logging functionality to a subset of privileged users"
          nist_control: "3.3.9"
          azure_implementation: "Azure AD PIM, Custom Roles"
          automated: true

    # Configuration Management (CM) - 7 practices
    configuration_management:
      domain_id: "CM"
      name: "Configuration Management"
      description: "Establish and maintain baseline configurations and inventories"
      practices_count: 7
      practices:
        - id: "CM.2.061"
          title: "Establish and maintain baseline configurations and inventories"
          nist_control: "3.4.1"
          azure_implementation: "Azure Policy, Security Center"
          automated: true
        - id: "CM.2.062"
          title: "Employ the principle of least functionality"
          nist_control: "3.4.2"
          azure_implementation: "Azure Policy, Application Control"
          automated: true
        - id: "CM.2.063"
          title: "Control and monitor user-installed software"
          nist_control: "3.4.3"
          azure_implementation: "Microsoft Intune, Application Control"
          automated: true
        - id: "CM.2.064"
          title: "Analyze the security impact of changes prior to implementation"
          nist_control: "3.4.4"
          azure_implementation: "Azure DevOps, Security Testing"
          automated: false
        - id: "CM.2.065"
          title: "Track, review, approve/disapprove, and audit changes to information systems"
          nist_control: "3.4.5"
          azure_implementation: "Azure DevOps, ARM Templates"
          automated: true
        - id: "CM.2.066"
          title: "Employ the principle of least functionality by configuring information systems"
          nist_control: "3.4.6"
          azure_implementation: "Azure Security Benchmarks, CIS Controls"
          automated: true
        - id: "CM.2.067"
          title: "Restrict, disable, or prevent the use of nonessential programs"
          nist_control: "3.4.7"
          azure_implementation: "Application Control, AppLocker"
          automated: true

    # Identification and Authentication (IA) - 12 practices
    identification_authentication:
      domain_id: "IA"
      name: "Identification and Authentication"
      description: "Identify information system users, processes, or devices"
      practices_count: 12
      practices:
        - id: "IA.1.076"
          title: "Identify information system users, processes acting on behalf of users, or devices"
          nist_control: "3.5.1"
          azure_implementation: "Azure AD, Managed Identity"
          automated: true
        - id: "IA.1.077"
          title: "Authenticate (or verify) the identities of those users, processes, or devices"
          nist_control: "3.5.2"
          azure_implementation: "Azure AD, MFA"
          automated: true
        - id: "IA.2.078"
          title: "Use multifactor authentication for local and network access to privileged accounts"
          nist_control: "3.5.3"
          azure_implementation: "Azure AD MFA, Conditional Access"
          automated: true
        - id: "IA.2.079"
          title: "Employ replay-resistant authentication mechanisms for network access to privileged accounts"
          nist_control: "3.5.4"
          azure_implementation: "Kerberos, Azure AD"
          automated: true
        - id: "IA.2.080"
          title: "Prevent reuse of identifiers for a defined period"
          nist_control: "3.5.5"
          azure_implementation: "Azure AD Identity Protection"
          automated: true
        - id: "IA.2.081"
          title: "Disable identifiers after a defined period of inactivity"
          nist_control: "3.5.6"
          azure_implementation: "Azure AD Identity Protection"
          automated: true
        - id: "IA.2.082"
          title: "Enforce a minimum password complexity and change of characters"
          nist_control: "3.5.7"
          azure_implementation: "Azure AD Password Policies"
          automated: true
        - id: "IA.2.083"
          title: "Prohibit password reuse for a specified number of generations"
          nist_control: "3.5.8"
          azure_implementation: "Azure AD Password History"
          automated: true
        - id: "IA.2.084"
          title: "Allow temporary password use for system logons with an immediate change to permanent password"
          nist_control: "3.5.9"
          azure_implementation: "Azure AD Password Reset"
          automated: true
        - id: "IA.2.085"
          title: "Store and transmit only cryptographically-protected passwords"
          nist_control: "3.5.10"
          azure_implementation: "Azure AD, Key Vault"
          automated: true
        - id: "IA.2.086"
          title: "Obscure feedback of authentication information"
          nist_control: "3.5.11"
          azure_implementation: "Windows Security Policy"
          automated: true

# Data Classification Labels for CUI
data_classification:
  cui_markings:
    - name: "CUI"
      description: "Controlled Unclassified Information"
      color: "#FF0000"
      priority: 90
      protection_level: "high"
      retention_period: "7_years"
      
    - name: "CUI//SP-ITAR" 
      description: "CUI Specified - International Traffic in Arms Regulations"
      color: "#8B0000"
      priority: 95
      protection_level: "highest"
      retention_period: "permanent"
      
    - name: "CUI//SP-EXPT"
      description: "CUI Specified - Export Controlled Technical Data"
      color: "#DC143C"
      priority: 92
      protection_level: "highest"
      retention_period: "7_years"
      
    - name: "CUI//SP-PRVCY"
      description: "CUI Specified - Privacy Information"
      color: "#B22222"
      priority: 88
      protection_level: "high"
      retention_period: "7_years"

  information_protection_labels:
    - name: "Public"
      guid: "00000000-0000-0000-0000-000000000000"
      description: "Information that can be shared publicly"
      protection_level: "none"
      
    - name: "Internal"
      guid: "11111111-1111-1111-1111-111111111111"
      description: "Internal organizational information"
      protection_level: "low"
      
    - name: "Confidential"
      guid: "22222222-2222-2222-2222-222222222222"
      description: "Confidential business information"
      protection_level: "medium"
      encryption: true
      
    - name: "Highly Confidential"
      guid: "33333333-3333-3333-3333-333333333333"
      description: "Highly sensitive business information"
      protection_level: "high"
      encryption: true
      watermarking: true
      
    - name: "CUI"
      guid: "44444444-4444-4444-4444-444444444444"
      description: "Controlled Unclassified Information"
      protection_level: "highest"
      encryption: true
      watermarking: true
      dlp_enabled: true

# Compliance Monitoring Configuration
compliance_monitoring:
  assessment_schedule: "daily"
  reporting_frequency: "weekly"
  
  automated_controls:
    - control: "AC.2.007"
      check: "azure_rbac_least_privilege"
      frequency: "daily"
      remediation: "automatic"
      
    - control: "AU.2.042"
      check: "audit_log_retention"
      frequency: "daily"
      remediation: "alert"
      
    - control: "IA.2.078"
      check: "mfa_enforcement"
      frequency: "hourly"
      remediation: "automatic"
      
    - control: "SC.2.179"
      check: "encryption_at_rest"
      frequency: "daily"
      remediation: "automatic"

  manual_controls:
    - control: "CM.2.064"
      check: "change_security_analysis"
      frequency: "per_change"
      owner: "Security Team"
      
    - control: "IR.2.092"
      check: "incident_response_testing"
      frequency: "quarterly"
      owner: "Incident Response Team"

# Azure Service Mappings for CMMC Controls
azure_service_mappings:
  identity_access:
    - service: "Azure Active Directory"
      controls: ["AC", "IA"]
      configuration:
        conditional_access: "enabled"
        mfa: "required"
        privileged_identity_management: "enabled"
        
  security_monitoring:
    - service: "Azure Sentinel"
      controls: ["AU", "IR", "SI"]
      configuration:
        data_connectors: "all_azure_services"
        retention_days: 365
        automated_response: "enabled"
        
  data_protection:
    - service: "Microsoft Purview"
      controls: ["MP", "RA"]
      configuration:
        data_classification: "automatic"
        sensitivity_labels: "enforced"
        dlp_policies: "enabled"
        
  encryption:
    - service: "Azure Key Vault"
      controls: ["SC"]
      configuration:
        hsm_backed: true
        key_rotation: "automatic"
        access_policies: "rbac"

# Incident Response Playbooks for CMMC
incident_response:
  cui_data_breach:
    severity: "high"
    response_time: "1_hour"
    stakeholders: ["CISO", "Legal", "Contracting Officer"]
    procedures:
      - "Isolate affected systems"
      - "Preserve forensic evidence"
      - "Notify DoD Contracting Officer within 72 hours"
      - "Document all actions taken"
      - "Conduct post-incident review"
      
  privileged_account_compromise:
    severity: "critical"
    response_time: "30_minutes"
    stakeholders: ["CISO", "IT Director", "Security Team"]
    procedures:
      - "Immediately disable compromised accounts"
      - "Force password reset for all privileged accounts"
      - "Review all privileged account activities"
      - "Implement additional monitoring"
      
  malware_detection:
    severity: "medium"
    response_time: "2_hours"
    stakeholders: ["Security Team", "IT Operations"]
    procedures:
      - "Isolate infected systems"
      - "Run full system scans"
      - "Update antimalware signatures"
      - "Review network traffic for indicators"