#!/bin/bash
#------------------------------------------------------------------------------
# GCP Landing Zone - Terraform State Backend Setup
#------------------------------------------------------------------------------
# Creates GCS bucket and enables versioning for Terraform state management
# Run this script once before initializing Terraform environments
#------------------------------------------------------------------------------

set -e

# Configuration
PROJECT_ID="${GCP_PROJECT_ID:-}"
BUCKET_NAME="${TF_STATE_BUCKET:-terraform-state-glz}"
BUCKET_LOCATION="${TF_STATE_LOCATION:-US}"
STATE_PREFIX="${TF_STATE_PREFIX:-terraform/state}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"

    if ! command -v gcloud &> /dev/null; then
        print_error "gcloud CLI is not installed"
        exit 1
    fi
    print_success "gcloud CLI found"

    if [ -z "$PROJECT_ID" ]; then
        print_warning "GCP_PROJECT_ID not set, attempting to get from gcloud config"
        PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
        if [ -z "$PROJECT_ID" ]; then
            print_error "Could not determine project ID"
            print_error "Set GCP_PROJECT_ID environment variable or run: gcloud config set project <PROJECT_ID>"
            exit 1
        fi
    fi
    print_success "Project ID: $PROJECT_ID"

    # Check authentication
    if ! gcloud auth print-access-token &> /dev/null; then
        print_error "Not authenticated with gcloud"
        print_error "Run: gcloud auth login"
        exit 1
    fi
    print_success "gcloud authentication verified"
}

# Create GCS bucket for state
create_state_bucket() {
    print_header "Creating State Bucket"

    FULL_BUCKET_NAME="${BUCKET_NAME}-${PROJECT_ID}"

    if gsutil ls -b "gs://${FULL_BUCKET_NAME}" &> /dev/null; then
        print_warning "Bucket gs://${FULL_BUCKET_NAME} already exists"
    else
        echo "Creating bucket gs://${FULL_BUCKET_NAME}..."
        gsutil mb -p "$PROJECT_ID" -l "$BUCKET_LOCATION" -b on "gs://${FULL_BUCKET_NAME}"
        print_success "Bucket created: gs://${FULL_BUCKET_NAME}"
    fi

    # Enable versioning
    echo "Enabling versioning..."
    gsutil versioning set on "gs://${FULL_BUCKET_NAME}"
    print_success "Versioning enabled"

    # Set lifecycle rule for old versions
    echo "Setting lifecycle rules..."
    cat > /tmp/lifecycle.json << 'EOF'
{
  "lifecycle": {
    "rule": [
      {
        "action": {"type": "Delete"},
        "condition": {
          "numNewerVersions": 5,
          "isLive": false
        }
      }
    ]
  }
}
EOF
    gsutil lifecycle set /tmp/lifecycle.json "gs://${FULL_BUCKET_NAME}"
    rm /tmp/lifecycle.json
    print_success "Lifecycle rules configured"

    # Set uniform bucket-level access
    echo "Setting uniform bucket-level access..."
    gsutil uniformbucketlevelaccess set on "gs://${FULL_BUCKET_NAME}"
    print_success "Uniform bucket-level access enabled"
}

# Create backend configuration file
create_backend_config() {
    print_header "Creating Backend Configuration"

    FULL_BUCKET_NAME="${BUCKET_NAME}-${PROJECT_ID}"

    for ENV in prod test dr; do
        ENV_DIR="../../environments/${ENV}"
        BACKEND_FILE="${ENV_DIR}/backend.tfvars"

        if [ -d "$ENV_DIR" ]; then
            cat > "$BACKEND_FILE" << EOF
# Terraform Backend Configuration - ${ENV}
# Auto-generated by state-backend.sh

bucket = "${FULL_BUCKET_NAME}"
prefix = "${STATE_PREFIX}/${ENV}"
EOF
            print_success "Created ${BACKEND_FILE}"
        fi
    done
}

# Print summary
print_summary() {
    print_header "Setup Complete"

    FULL_BUCKET_NAME="${BUCKET_NAME}-${PROJECT_ID}"

    echo ""
    echo "State Bucket: gs://${FULL_BUCKET_NAME}"
    echo "Location:     ${BUCKET_LOCATION}"
    echo "State Prefix: ${STATE_PREFIX}"
    echo ""
    echo "To initialize Terraform for an environment:"
    echo ""
    echo "  cd environments/prod"
    echo "  terraform init -backend-config=backend.tfvars"
    echo ""
    echo "Or use the eo-deploy.sh wrapper:"
    echo ""
    echo "  cd environments/prod"
    echo "  ./eo-deploy.sh init"
    echo ""
}

# Main
main() {
    echo ""
    print_header "GCP Landing Zone - State Backend Setup"
    echo ""

    check_prerequisites
    create_state_bucket
    create_backend_config
    print_summary
}

main "$@"
