---
# Dell PowerSwitch Datacenter Network Deployment Playbook
# Automates deployment of Dell PowerSwitch datacenter switching infrastructure

- name: Dell PowerSwitch Datacenter Network Deployment
  hosts: all
  gather_facts: true
  become: false
  vars:
    deployment_timestamp: "{{ ansible_date_time.epoch }}"
    backup_dir: "/tmp/powerswitch_backups/{{ deployment_timestamp }}"
    
  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Display deployment banner
      debug:
        msg: |
          ================================================================
          Dell PowerSwitch Datacenter Network Deployment
          Timestamp: {{ ansible_date_time.iso8601 }}
          Target Switches: {{ ansible_play_hosts | length }}
          ================================================================

# Leaf Switch Configuration
- name: Configure Leaf Switches
  hosts: leaf_switches
  gather_facts: false
  vars:
    leaf_config:
      vlt_domain: "{{ hostvars[inventory_hostname]['vlt_domain'] | default(1) }}"
      vlt_peer: "{{ hostvars[inventory_hostname]['vlt_peer'] }}"
      
  tasks:
    - name: Backup leaf switch configuration
      dellos9_command:
        commands:
          - show running-config
      register: leaf_backup

    - name: Save leaf switch backup
      copy:
        content: "{{ leaf_backup.stdout[0] }}"
        dest: "{{ backup_dir }}/leaf_{{ inventory_hostname }}_backup.cfg"
      delegate_to: localhost

    - name: Configure VLT domain
      dellos9_config:
        lines:
          - vlt domain {{ leaf_config.vlt_domain }}
          - peer-link port-channel 1
          - back-up destination {{ leaf_config.vlt_peer }}
          - system-mac mac-address-format
          - unit-id {{ hostvars[inventory_hostname]['vlt_unit_id'] | default(0) }}

    - name: Configure port channels for VLT
      dellos9_config:
        lines:
          - interface port-channel {{ item.id }}
          - description {{ item.description }}
          - switchport mode trunk
          - switchport trunk allowed vlan {{ item.vlans }}
          - vlt-port-channel {{ item.id }}
          - no shutdown
      loop: "{{ port_channels | default([]) }}"

    - name: Configure access ports
      dellos9_config:
        lines:
          - interface {{ item.interface }}
          - description {{ item.description }}
          - switchport mode access
          - switchport access vlan {{ item.vlan }}
          - spanning-tree port type edge
          - no shutdown
      loop: "{{ access_ports | default([]) }}"

# Spine Switch Configuration  
- name: Configure Spine Switches
  hosts: spine_switches
  gather_facts: false
  tasks:
    - name: Backup spine switch configuration
      dellos9_command:
        commands:
          - show running-config
      register: spine_backup

    - name: Save spine switch backup
      copy:
        content: "{{ spine_backup.stdout[0] }}"
        dest: "{{ backup_dir }}/spine_{{ inventory_hostname }}_backup.cfg"
      delegate_to: localhost

    - name: Configure BGP for spine
      dellos9_config:
        lines:
          - router bgp {{ bgp_asn }}
          - router-id {{ hostvars[inventory_hostname]['loopback_ip'] }}
          - neighbor {{ item.peer_ip }} remote-as {{ item.remote_asn }}
          - neighbor {{ item.peer_ip }} description {{ item.description }}
          - address-family ipv4 unicast
          - redistribute connected
      loop: "{{ bgp_neighbors | default([]) }}"

# VLAN Configuration
- name: Configure VLANs
  hosts: leaf_switches
  gather_facts: false
  tasks:
    - name: Create VLANs
      dellos9_config:
        lines:
          - vlan {{ item.id }}
          - name {{ item.name }}
          - description {{ item.description }}
      loop: "{{ vlans | default([]) }}"

    - name: Configure SVI interfaces
      dellos9_config:
        lines:
          - interface vlan {{ item.id }}
          - description {{ item.description }}
          - ip address {{ item.ip_address }} {{ item.subnet_mask }}
          - no shutdown
      loop: "{{ svi_interfaces | default([]) }}"

# Quality of Service
- name: Configure QoS policies
  hosts: all
  gather_facts: false
  tasks:
    - name: Create QoS class maps
      dellos9_config:
        lines:
          - class-map {{ item.name }}
          - match {{ item.match_criteria }}
      loop: "{{ qos_class_maps | default([]) }}"

    - name: Create QoS policy maps
      dellos9_config:
        lines:
          - policy-map {{ item.name }}
          - class {{ item.class_name }}
          - "{% if item.action == 'set-dscp' %}set dscp {{ item.value }}{% endif %}"
          - "{% if item.action == 'police' %}police {{ item.rate }} {{ item.burst }}{% endif %}"
      loop: "{{ qos_policy_maps | default([]) }}"

# Security Configuration
- name: Configure security features
  hosts: all
  gather_facts: false
  tasks:
    - name: Enable AAA authentication
      dellos9_config:
        lines:
          - aaa authentication login default local
          - aaa authentication enable default enable
          - aaa authorization exec default local

    - name: Configure access control lists
      dellos9_config:
        lines:
          - ip access-list standard {{ item.name }}
          - "{% for rule in item.rules %}{{ rule }}{% endfor %}"
      loop: "{{ access_lists | default([]) }}"

    - name: Enable storm control
      dellos9_config:
        lines:
          - interface {{ item.interface }}
          - storm-control broadcast 10
          - storm-control multicast 10
          - storm-control unicast 10
      loop: "{{ storm_control_interfaces | default([]) }}"

# Monitoring and SNMP
- name: Configure monitoring
  hosts: all
  gather_facts: false  
  tasks:
    - name: Configure SNMP
      dellos9_config:
        lines:
          - snmp-server community {{ snmp_community | default('public') }} ro
          - snmp-server location {{ snmp_location | default('Datacenter') }}
          - snmp-server contact {{ snmp_contact | default('admin@company.com') }}
          - snmp-server enable traps

    - name: Configure syslog
      dellos9_config:
        lines:
          - logging {{ item.server }}
          - logging facility {{ item.facility | default('local0') }}
          - logging level {{ item.level | default('informational') }}
      loop: "{{ syslog_servers | default([]) }}"

# Final verification
- name: Verify deployment
  hosts: all
  gather_facts: false
  tasks:
    - name: Show switch status
      dellos9_command:
        commands:
          - show system
          - show interface status
          - show vlan brief
          - show ip interface brief
      register: verification_output

    - name: Display verification results
      debug:
        msg: |
          Switch: {{ inventory_hostname }}
          System Status: {{ verification_output.stdout[0] | regex_search('System Status.*') }}
          Interface Count: {{ verification_output.stdout[1] | regex_findall('Ethernet') | length }}
          VLAN Count: {{ verification_output.stdout[2] | regex_findall('[0-9]+') | length }}

# Generate deployment report
- name: Generate deployment report
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Create deployment summary
      template:
        src: dell_powerswitch_report.j2
        dest: "{{ backup_dir }}/deployment_report.html"
      vars:
        deployment_summary:
          timestamp: "{{ ansible_date_time.iso8601 }}"
          total_switches: "{{ groups['all'] | length }}"
          leaf_switches: "{{ groups['leaf_switches'] | default([]) | length }}"
          spine_switches: "{{ groups['spine_switches'] | default([]) | length }}"
          backup_location: "{{ backup_dir }}"

    - name: Display completion summary
      debug:
        msg: |
          ================================================================
          Dell PowerSwitch Datacenter Deployment Complete
          Total Switches: {{ groups['all'] | length }}
          Leaf Switches: {{ groups['leaf_switches'] | default([]) | length }}
          Spine Switches: {{ groups['spine_switches'] | default([]) | length }}
          Backup Location: {{ backup_dir }}
          ================================================================